export const SEED_FLAVORS = [
  {
    id: "classic-cinnamon",
    name: "Classic Cinnamon",
    slug: "classic-cinnamon",
    pricePerPiece: 4,
    isClassic: true,
    imageUrl: "",
    active: true,
    sortOrder: 0,
  },
  {
    id: "tiramisu",
    name: "Tiramisu",
    slug: "tiramisu",
    pricePerPiece: 5,
    isClassic: false,
    imageUrl: "",
    active: true,
    sortOrder: 1,
  },
  {
    id: "caramel-pecan",
    name: "Caramel Pecan",
    slug: "caramel-pecan",
    pricePerPiece: 5,
    isClassic: false,
    imageUrl: "",
    active: true,
    sortOrder: 2,
  },
  {
    id: "lotus",
    name: "Lotus",
    slug: "lotus",
    pricePerPiece: 5,
    isClassic: false,
    imageUrl: "",
    active: true,
    sortOrder: 3,
  },
  {
    id: "oreo",
    name: "Oreo",
    slug: "oreo",
    pricePerPiece: 5,
    isClassic: false,
    imageUrl: "",
    active: true,
    sortOrder: 4,
  },
  {
    id: "hot-chocolate",
    name: "Hot Chocolate",
    slug: "hot-chocolate",
    pricePerPiece: 5,
    isClassic: false,
    imageUrl: "",
    active: true,
    sortOrder: 5,
  },
  {
    id: "apple-pie",
    name: "Apple Pie",
    slug: "apple-pie",
    pricePerPiece: 5,
    isClassic: false,
    imageUrl: "",
    active: true,
    sortOrder: 6,
  },
];

export const SEED_PACKAGE_TIERS = [
  { id: "tier-1", pieceCount: 1, classicPrice: 4, otherFlavorPrice: 5, freeDelivery: false },
  { id: "tier-4", pieceCount: 4, classicPrice: 14, otherFlavorPrice: 18, freeDelivery: false },
  { id: "tier-6", pieceCount: 6, classicPrice: 21, otherFlavorPrice: 27, freeDelivery: false },
  { id: "tier-9", pieceCount: 9, classicPrice: 31, otherFlavorPrice: 40, freeDelivery: false },
  { id: "tier-12", pieceCount: 12, classicPrice: 42, otherFlavorPrice: 54, freeDelivery: false },
  { id: "tier-24", pieceCount: 24, classicPrice: 84, otherFlavorPrice: 108, freeDelivery: true },
];

export const SEED_MINI_BOX = {
  name: "Signature Mini Box",
  totalPieces: 12,
  price: 20,
  freeDelivery: true,
  eligibleFlavorIds: [
    "classic-cinnamon",
    "lotus",
    "oreo",
    "caramel-pecan",
    "apple-pie",
    "tiramisu",
  ],
};

export const SEED_SETTINGS = {
  whatsappNumber: "96178904118",
  deliveryCharge: 4,
  deliveryFreeThreshold: "24 pieces or Signature Mini Box",
  storeName: "Sarah's Bakery",
  heroImageUrl: "",
  logoUrl: "",
  heroHeadline: "Cinnamon rolls, rolled fresh in Lebanon.",
  heroTagline: "you choose, we make it",
  preOrderNote: "Please order a day ahead — every roll is made fresh, not stocked.",
  instagramUrl: "#",
  facebookUrl: "#",
  tiktokUrl: "#",
};
